### ISSUE TITLE
关于yolov7模型输入输出名称的问题

### ISSUE THREAD

**Issue by HZNUJeffreyRen** [Baiyuetribe/ncnn-models#8]
大佬你好，我看了你yolov7 ncnn推理的代码，你的输入输出名称是"in0"、“out0”、“out1”、“out2”，请问你是怎么设置的？我执行python export.py导出的模型名称是"images"和“output”，还有两个输出我不知道叫啥名称。。。

请问你export.py这个脚本是不是漏了啥代码，没有设置输入输出的名称？

**Comment by Baiyuetribe** [comment]
啥都没露，是你自我内耗了，就两三行转换代码，执行完毕就得到结果了。pnnx转换得到你说的in0~out0; onnx2ncnn不是我写的教程
